# Generated by Django 5.2.5 on 2025-09-08 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('additional_title', models.CharField(max_length=200)),
                ('additional_description', models.TextField()),
            ],
            options={
                'db_table': 'about_us_page',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('slide1', models.ImageField(blank=True, null=True, upload_to='slides1/')),
                ('slide2', models.ImageField(blank=True, null=True, upload_to='slides2/')),
                ('slide3', models.ImageField(blank=True, null=True, upload_to='slides3/')),
            ],
            options={
                'db_table': 'main_page',
            },
        ),
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
            ],
            options={
                'db_table': 'seo',
            },
        ),
        migrations.CreateModel(
            name='AboutUsPageDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='about_files/')),
                ('about_us_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.aboutuspage')),
            ],
            options={
                'db_table': 'about_us_page_documents',
            },
        ),
        migrations.CreateModel(
            name='AboutUsPageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.aboutuspage')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.images')),
            ],
            options={
                'db_table': 'about_us_gallery',
            },
        ),
        migrations.CreateModel(
            name='AboutUsPageAdditionalGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.aboutuspage')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.images')),
            ],
            options={
                'db_table': 'about_us_gallery_additional',
            },
        ),
        migrations.CreateModel(
            name='MainPageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='main_page/')),
                ('main_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.mainpage')),
            ],
            options={
                'db_table': 'main_page_block',
            },
        ),
        migrations.AddField(
            model_name='mainpage',
            name='seo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.seo'),
        ),
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link_site', models.URLField()),
                ('map', models.TextField()),
                ('fio', models.CharField(max_length=200)),
                ('location', models.TextField(max_length=200)),
                ('address', models.TextField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.seo')),
            ],
            options={
                'db_table': 'contacts_page',
            },
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='seo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.seo'),
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.seo')),
            ],
            options={
                'db_table': 'service_page',
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='service_card/')),
                ('service_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.servicepage')),
            ],
            options={
                'db_table': 'service_card',
            },
        ),
        migrations.CreateModel(
            name='TariffsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.seo')),
            ],
            options={
                'db_table': 'tariffs_page',
            },
        ),
        migrations.CreateModel(
            name='TariffsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=200)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='tariffs_card/')),
                ('tariffs_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.tariffspage')),
            ],
            options={
                'db_table': 'tariffs_card',
            },
        ),
    ]
