# Generated by Django 5.2.5 on 2025-09-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='description',
            field=models.TextField(),
        ),
    ]
