# Generated by Django 5.2.5 on 2025-09-03 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате: +380XXXXXXXXX', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('active', 'Активен'), ('inactive', 'Отключен')], default='new', max_length=32),
        ),
    ]
