# Generated by Django 5.2.5 on 2025-09-01 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetailsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('information', models.TextField()),
            ],
            options={
                'db_table': 'payment_details_settings',
            },
        ),
        migrations.CreateModel(
            name='PaymentItemsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('translation_type', models.CharField(choices=[('income', 'Приход'), ('expense', 'Расход')], default='income', max_length=10)),
            ],
            options={
                'db_table': 'payment_items_settings',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_statistics', models.BooleanField(default=False)),
                ('has_cash_desk', models.BooleanField(default=False)),
                ('has_receipt', models.BooleanField(default=False)),
                ('has_personal_accounts', models.BooleanField(default=False)),
                ('has_apartments', models.BooleanField(default=False)),
                ('has_owner', models.BooleanField(default=False)),
                ('has_houses', models.BooleanField(default=False)),
                ('has_message', models.BooleanField(default=False)),
                ('has_request', models.BooleanField(default=False)),
                ('has_counters', models.BooleanField(default=False)),
                ('has_site_management', models.BooleanField(default=False)),
                ('has_services', models.BooleanField(default=False)),
                ('has_tariffs', models.BooleanField(default=False)),
                ('has_job_title', models.BooleanField(default=False)),
                ('has_users', models.BooleanField(default=False)),
                ('has_payment_details', models.BooleanField(default=False)),
                ('job_title', models.CharField(choices=[('director', 'Директор'), ('manager', 'Управляющий'), ('accountant', 'Бухгалтер'), ('electrician', 'Электрик'), ('plumber', 'Сантехник')], max_length=20)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='ServiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_counters', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'service_settings',
            },
        ),
        migrations.CreateModel(
            name='TariffsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tariffs_settings',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='UnitsMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'units_measurement',
            },
        ),
        migrations.CreateModel(
            name='PriceTariffSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system_settings.servicesettings')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_settings.tariffssettings')),
            ],
            options={
                'db_table': 'price_tariff_settings',
            },
        ),
        migrations.AddField(
            model_name='servicesettings',
            name='units_measurement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_settings', to='system_settings.unitsmeasurement'),
        ),
    ]
