# Generated by Django 5.2.5 on 2025-08-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesettings',
            name='is_counters',
            field=models.BooleanField(default=False),
        ),
    ]
