# Generated by Django 5.2.5 on 2025-08-29 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0002_servicesettings_is_counters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesettings',
            name='units_measurement',
            field=models.ForeignKey(default='manager', on_delete=django.db.models.deletion.CASCADE, related_name='service_settings', to='system_settings.unitsmeasurement'),
        ),
        migrations.CreateModel(
            name='PriceTariffSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_settings.servicesettings')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_settings.tariffssettings')),
            ],
            options={
                'db_table': 'price_tariff_settings',
            },
        ),
    ]
