# Generated by Django 5.2.5 on 2025-08-29 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0003_alter_servicesettings_units_measurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesettings',
            name='units_measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_settings', to='system_settings.unitsmeasurement'),
        ),
    ]
