# Generated by Django 5.2.5 on 2025-08-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0005_alter_servicesettings_units_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesettings',
            name='title',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
