# Generated by Django 5.2.5 on 2025-08-29 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0006_alter_servicesettings_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetariffsettings',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system_settings.servicesettings'),
        ),
        migrations.AlterField(
            model_name='servicesettings',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
