# Generated by Django 5.2.5 on 2025-09-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0007_alter_pricetariffsettings_service_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariffssettings',
            options={'ordering': ('-id',)},
        ),
        migrations.AddIndex(
            model_name='servicesettings',
            index=models.Index(fields=['units_measurement', 'is_counters'], name='service_set_units_m_23462e_idx'),
        ),
    ]
